############################################################

service:
 # service name
 name: application-access-point
 
 # type of service can be ClusterIP, LoadBalancer, NodePort 
 type: ClusterIP
 
 # define title of service selector.
 selectorName: web-serv

 #port settings of the current service
 ports:
   port: 8020
   protocol: TCP
 externalIPs:
 - 192.168.100.126


#############################################################

deployment: 
 
 # deployment name
 name: deployment-web-servers
 
 # define quantity of 
 replicaCount: 3
 minReadySeconds: 10
 
 # define strategy of rolling-out pods
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0
 
 # define selector of ReplicaSet
 selector:
  app: web-serv

 # define characteristics of pod
 template:
  name: web-server
  labels:
    app: web-serv
  
  # define characteristics of container 
  spec:
   containers:
    repo: tide34
    image: custom
    tag: latest
    name: httpd
    imagePullPolicy: Always
    
    readynessProbe:
     initialDelaySeconds: 20
     periodSeconds: 5
     containerPort: 80
  
    volumeMounts:
     destPath: /usr/local/apache2/htdocs  
  
  volume:
   name: web-page-files
   type: Directory
   path: /home/folderToStoreFileFromJenkins 
