apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.deploymentName | quote }}
spec:
 replicas: {{ .Values.replicaCount }}
 minReadySeconds: {{ .Values.minReadySeconds }}
 strategy:
  rollingUpdate:
    maxSurge: {{ .Values.rollingUpdate.maxSurge }}
    maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  type: {{ .Values.strategyType | quote }}
 selector:
  matchLabels:
   app: {{ .Values.deploymentSelector.app | quote }}
 template:
  metadata:
   name: {{ .Values.podTemplate.name | quote }}
   labels:
    app: {{ .Values.podTemplate.labels.app | quote }}
  spec:
   containers:
   - image: {{ .Values.containers.repo }}/{{ .Values.containers.image }}:{{ .Values.containers.tag }}
     name: {{ .Values.containers.name | quote }}
     imagePullPolicy: {{ .Values.containers.imagePullPolicy | quote }}
     readinessProbe:
      initialDelaySeconds: {{ .Values.containers.readynessProbe.initialDelaySeconds }}
      periodSeconds: {{ .Values.containers.readynessProbe.periodSeconds }}
      httpGet:
       path: /
       port: {{ .Values.containers.readynessProbe.containerPort }}
     volumeMounts:
     - mountPath: {{ .Values.containers.volumeMounts.destPath | quote }}
       name: {{ .Values.volume.name | quote }}
     resources:
      requests:
       cpu: {{ .Values.containers.resources.reqCPU }}
       memory: {{ .Values.containers.resources.reqMemory }}
      limits:
       cpu: {{ .Values.containers.resources.limCPU }}
       memory: {{ .Values.containers.resources.limMemory }}
   volumes:
   - name: {{ .Values.volume.name | quote }}
     hostPath:
       path: {{ .Values.volume.path | quote }}
       type: {{ .Values.volume.type | quote }}
